In [1]:
import pandas as pd
import sys
import numpy as np
import os
import csv
%matplotlib inline

In [2]:
df = pd.read_csv("100000.csv")

In [3]:
num_rows = 100000

In [4]:
write_folder = str(num_rows)

In [129]:
# Create the folder if it already doesn't exist
if not os.path.exists(write_folder):
    os.makedirs(write_folder)

In [130]:
df.to_csv(write_folder+"//"+write_folder+".csv",index=False)

In [5]:
# df = pd.read_csv(write_folder+"//10000.csv")

In [6]:
df

,Unnamed: 0,transaction_id,counter_id,branch_id,date_of_transaction,hour,high_level_territory,staff_id,product_id,payment_amount,BeaAdmin,cust_id,name,plate_no,installment,date
0,0,800474,46261-1,46261,20170309,95720,5,966272407,F030C,570000,5000,32013000346016,DIDI WARSIDI,Z6329VW,5,20170311
1,1,800475,45565-3,45565,20170309,111620,5,984394898,F030C,328000,5000,32010000372715,EDO,E4711ZU,21,20170310
2,2,800476,40553-15,40553,20170310,80120,5,981376812,F030C,915000,5000,32005000292815,CECEP AHMAD FAUZI,D2710UBZ,23,20170309
3,3,800477,46155-4,46155,20170310,93220,5,969317864,F030C,705000,5000,32002000538615,DEDE SAODAH,Z3842PL,19,20170311
4,4,800478,41100-21,41100,20170310,175020,5,994440832,F030C,440000,5000,32009000047215,DEDE RUDI,T6986CF,23,20170310
5,5,800479,40767B1-8,40767B1,20170311,85720,5,968272198,F030C,590000,5000,32005000111615,ADE SUHERMAN,D3497UBX,25,20170311
6,6,800480,46100-2,46100,20170311,105320,5,315006973,F030C,570000,5000,32002000272814,ASEP SUPRIATNA,Z4601LN,34,20170313
7,7,800481,40500-30,40500,20170313,91820,5,990403658,F030C,780000,5000,32005000179615,IYAN,D5565SAR,25,20170328
8,8,800482,40225A-7,40225A,20170313,80220,5,967322807,F030C,667000,5000,32003000432116,ATEP NUGRAHA,D5464UCQ,7,20170312
9,9,800483,45153-2,45153,20170313,95220,5,964234695,F030C,280000,5000,33010000469815,DAYU BUDI SETIAWAN,AA5042YK,15,20170228
10,10,800484,45200-16,45200,20170313,81020,5,985394640,F030C,545000,5000,34007000532814,NANANG ABDULLAH,P6739TZ,30,20170413
11,11,800485,46387-3,46387,20170313,133620,5,313004107,F030C,505000,5000,32013000638915,TAUFIK HIDAYAT,Z6050VG,16,20170318
12,12,800486,40500-8,40500,20170314,103820,5,979438380,F030C,760000,5000,32005000838615,PERMANA HERLAMBANG,D5266SAT,18,20170314
13,13,800487,"4,09E+05-2","4,09E+05",20170314,110720,5,316000182,F030C,940000,5000,32007000260316,ERY PERMANA,D5204ZCI,8,20170321
14,14,800488,46261-1,46261,20170314,135120,5,966272407,F030C,770000,5000,32013000397115,ARI JAENAL ARIFIN,Z6179VP,21,20170327
15,15,800489,40222A-8,40222A,20170315,104820,5,973387210,F030C,1195000,5000,32005000404316,DEDEN JUHARI,D5464AAK,7,20170315
16,16,800490,45186-5,45186,20170315,101420,5,313000867,F030C,495000,5000,32004000251316,TURMIN,E3120NS,8,20170319
17,17,800491,46262-2,46262,20170315,130720,5,969286302,F030C,1405000,5000,32013000245516,IDAS BUSTOMI,Z4295VV,8,20170315
18,18,800492,46263-1,46263,20170315,110420,5,967282743,F030C,1160000,5000,32002000663915,DODOY,Z6538VR,17,20170322
19,19,800493,44188-2,44188,20170316,105820,5,982440765,F030C,655000,5000,32012000262614,ABUD MUHAMAD ABDALLOH,Z3109FX,33,20170317
20,20,800494,45257-4,45257,20170316,94220,5,974363728,F030C,562000,5000,32010000625915,MISJA,E2743YAE,15,20170220
21,21,800495,41382-3,41382,20170317,133120,5,971366159,F030C,520000,5000,32008000255715,UPI SUPINI,T2878MW,21,20170319
22,22,800496,45583-2,45583,20170317,95620,5,979383742,F030C,795000,5000,32010000007617,CASRIMI,E4298YAK,2,20170320
23,23,800497,45181-2,45181,20170317,85020,5,964234749,F030C,530000,5000,32004000026616,ARISWONO,E3981NF,14,20170320
24,24,800498,46200-6,46200,20170317,103420,5,979383699,F030C,705000,5000,32013000127616,UDUNG ADI ISWARA,Z3487VU,11,20170323
25,25,800499,46474-1,46474,20170318,82720,5,963171770,F030C,665000,5000,32002000256016,DEDE MULYANA,Z2545PW,10,20170319
26,26,800500,40272A-7,40272A,20170318,85820,5,990437826,F030C,565000,5000,32007000746114,YANTO,D4819MK,27,20170308
27,27,800501,40383B2-3,40383B2,20170320,85820,5,967272452,F030C,685000,5000,32003000452114,GANTINA CAHYA NATARI,D6384VBO,34,20170323
28,28,800502,45181-2,45181,20170320,142620,5,964234749,F030C,442000,5000,32004000244114,WASILAH,E4902MX,33,20170325
29,29,800503,46254-1,46254,20170320,74220,5,965279248,F030C,589000,5000,32013000690815,RASTA,Z4092VS,15,20170318
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
99970,99970,900444,45500-13,45500,20170804,124020,5,313000894,F030C,1137000,5000,40003000220570,Sonya Dennis,S6658URM,3,20180328
99971,99971,900445,45561-2,45561,20171013,153820,5,985416373,F030C,426000,5000,40003000220571,Adam Johnson,H0738VVK,12,20170713
99972,99972,900446,45553-4,45553,20171014,114920,5,969332804,F030C,931000,5000,40003000220572,Michael Reynolds,R0253LW,18,20171010
99973,99973,900447,40123A-4,40123A,20170419,140220,5,971328778,F030C,937000,5000,40003000220573,Taylor Jackson,Z6443ZDH,21,20170316
99974,99974,900448,45186-5,45186,20170711,173920,5,313000867,F030C,328000,5000,40003000220574,Tyler Ortega,Y1068LMC,12,20170815
99975,99975,900449,46392-2,46392,20170922,82120,5,965298346,F030C,655000,5000,40003000220575,Sandra Smith,O6165BI,19,20170802
99976,99976,900450,46200-9,46200,20170331,93320,5,313000906,F030C,1185000,5000,40003000220576,Robert May,J9268DHC,13,20170711
99977,99977,900451,40553-17,40553,20170620,174920,5,988409288,F030C,714000,5000,40003000220577,Benjamin Allen,B6131EP,31,20170305
99978,99978,900452,40555-7,40555,20171006,175020,5,991438371,F030C,1192000,5000,40003000220578,Shannon Cobb,F7542ML,23,20170621
99979,99979,900453,45571-3,45571,20171215,203120,5,965242754,F030C,631000,5000,40003000220579,Michael Braun,L5267JY,14,20170925
99980,99980,900454,45181-2,45181,20170305,193320,5,964234749,F030C,421000,5000,40003000220580,Nicholas Banks,J9087QTM,12,20180215
99981,99981,900455,41162-4,41162,20170426,161720,5,971308949,F030C,734000,5000,40003000220581,Brandi Young,Y8726DM,31,20170905
99982,99982,900456,46261-1,46261,20170618,173020,5,966272407,F030C,1342000,5000,40003000220582,Paul Malone,H3533PBT,19,20170722
99983,99983,900457,45561-2,45561,20171231,71820,5,985416373,F030C,782000,5000,40003000220583,Allen Hill,J1125EJ,25,20170626
99984,99984,900458,40151B-2,40151B,20170508,70320,5,966251696,F030C,810000,5000,40003000220584,William James,B5539HFH,27,20171115
99985,99985,900459,40551-8,40551,20170519,75220,5,974363534,F030C,1061000,5000,40003000220585,Christine Dominguez,C1053KQW,13,20180224
99986,99986,900460,46100-16,46100,20170505,81920,5,989471792,F030C,494000,5000,40003000220586,John Andrews,M3084BDD,1,20170225
99987,99987,900461,40391-4,40391,20170703,131020,5,966269860,F030C,512000,5000,40003000220587,Kelly Barber,K6360BLD,13,20171122
99988,99988,900462,44171-11,44171,20170602,151220,5,964170930,F030C,813000,5000,40003000220588,David Miller,J3207HIF,27,20170529
99989,99989,900463,41165B1-1,41165B1,20170623,140420,5,966255562,F030C,1399000,5000,40003000220589,Carrie Allen,O4991KH,17,20171219
99990,99990,900464,40258-12,40258,20170521,85120,5,313006918,F030C,1675000,5000,40003000220590,Tara May,U5203CKR,22,20170804
99991,99991,900465,46153-2,46153,20170517,115820,5,968286860,F030C,493000,5000,40003000220591,Derek Wallace,M3859RJ,25,20170425
99992,99992,900466,45181-2,45181,20171023,173420,5,964234749,F030C,2235000,5000,40003000220592,Kenneth Price,C4190BLY,18,20170325
99993,99993,900467,45194-2,45194,20170510,163420,5,966303118,F030C,2360000,5000,40003000220593,Amanda Green,E5387AYT,14,20180509
99994,99994,900468,40153A-4,40153A,20170306,180020,5,969296459,F030C,618000,5000,40003000220594,Donna Duffy,S6339UVM,41,20171130
99995,99995,900469,40153A-6,40153A,20170516,200320,5,970328837,F030C,453000,5000,40003000220595,Anthony Blackwell,C0640JOW,9,20171023
99996,99996,900470,45163-1,45163,20170806,130620,5,963239648,F030C,1426000,5000,40003000220596,Brittany Pratt,S9178RO,42,20180130
99997,99997,900471,46100-4,46100,20171206,162620,5,315006971,F030C,1624000,5000,40003000220597,Ronald Harris,R1714OC,10,20170908
99998,99998,900472,46387-5,46387,20171207,184120,5,976385703,F030C,1097000,5000,40003000220598,Mr. Craig Graham,G4914IK,19,20180402
99999,99999,900473,45587-5,45587,20170825,101220,5,978384544,F030C,864000,5000,40003000220599,Kyle Jacobson,B4717IWQ,28,20180115

# Separate columns into csv files

Transaction Details

In [8]:
x=pd.DataFrame(df[["transaction_id","date_of_transaction","hour","installment","payment_amount","BeaAdmin"]],
             columns=["transaction_id","date_of_transaction","hour","installment","payment_amount","BeaAdmin"]
            ).reset_index().drop('index', 1).shift()[1:].to_csv(write_folder+"//transaction_details.csv",
                                                                index_label="transactionId:ID(Transaction)",
                                                                float_format="%.10g")

Staff Ids

In [134]:
pd.DataFrame(df["staff_id"].unique(),columns=["staff_id"]).drop_duplicates(subset="staff_id").reset_index().drop('index', 1).shift()[1:].to_csv(write_folder+"//staff_ids.csv",index=True,index_label="staffId:ID(Staff)",float_format="%.10g")

Customer Info

In [135]:
pd.DataFrame(df[["cust_id","name"]],
             columns=["cust_id","name"]).drop_duplicates(subset="cust_id").reset_index().drop('index', 1).shift()[1:].to_csv(write_folder+"//customer.csv",index=True,index_label = "customerId:ID(Customer)")

Vehicle info

In [136]:
pd.DataFrame(df[["plate_no"]],
             columns=["plate_no"]).drop_duplicates(subset="plate_no").reset_index().drop('index', 1).shift()[1:].to_csv(write_folder+"//vehicles.csv",index=True,index_label = "vehicleId:ID(Vehicle)",float_format="%.10g")

Branch ID

In [137]:
pd.DataFrame(df["branch_id"].unique(),columns=["branch_id"]).drop_duplicates(subset="branch_id").reset_index().drop('index', 1).shift()[1:].to_csv(write_folder+"//branches.csv",index=True,index_label = "branchId:ID(Branch)",float_format="%.10g")

Counter ids

In [138]:
pd.DataFrame(df["counter_id"].unique(),columns=["counter_id"]).drop_duplicates(subset="counter_id").reset_index().drop('index', 1).shift()[1:].to_csv(write_folder+"//counters.csv",index=True,index_label = "counterId:ID(Counter)",float_format="%.10g")

Main table with the foreign keys

In [139]:
df2 = pd.DataFrame(df[["transaction_id","staff_id","cust_id","plate_no","branch_id","counter_id"]],
             columns=["transaction_id","staff_id","cust_id","plate_no","branch_id","counter_id"])

In [140]:
df2

,transaction_id,staff_id,cust_id,plate_no,branch_id,counter_id
0,800474,966272407,32013000346016,Z6329VW,46261,46261-1
1,800475,984394898,32010000372715,E4711ZU,45565,45565-3
2,800476,981376812,32005000292815,D2710UBZ,40553,40553-15
3,800477,969317864,32002000538615,Z3842PL,46155,46155-4
4,800478,994440832,32009000047215,T6986CF,41100,41100-21
5,800479,968272198,32005000111615,D3497UBX,40767B1,40767B1-8
6,800480,315006973,32002000272814,Z4601LN,46100,46100-2
7,800481,990403658,32005000179615,D5565SAR,40500,40500-30
8,800482,967322807,32003000432116,D5464UCQ,40225A,40225A-7
9,800483,964234695,33010000469815,AA5042YK,45153,45153-2
10,800484,985394640,34007000532814,P6739TZ,45200,45200-16
11,800485,313004107,32013000638915,Z6050VG,46387,46387-3
12,800486,979438380,32005000838615,D5266SAT,40500,40500-8
13,800487,316000182,32007000260316,D5204ZCI,"4,09E+05","4,09E+05-2"
14,800488,966272407,32013000397115,Z6179VP,46261,46261-1
15,800489,973387210,32005000404316,D5464AAK,40222A,40222A-8
16,800490,313000867,32004000251316,E3120NS,45186,45186-5
17,800491,969286302,32013000245516,Z4295VV,46262,46262-2
18,800492,967282743,32002000663915,Z6538VR,46263,46263-1
19,800493,982440765,32012000262614,Z3109FX,44188,44188-2
20,800494,974363728,32010000625915,E2743YAE,45257,45257-4
21,800495,971366159,32008000255715,T2878MW,41382,41382-3
22,800496,979383742,32010000007617,E4298YAK,45583,45583-2
23,800497,964234749,32004000026616,E3981NF,45181,45181-2
24,800498,979383699,32013000127616,Z3487VU,46200,46200-6
25,800499,963171770,32002000256016,Z2545PW,46474,46474-1
26,800500,990437826,32007000746114,D4819MK,40272A,40272A-7
27,800501,967272452,32003000452114,D6384VBO,40383B2,40383B2-3
28,800502,964234749,32004000244114,E4902MX,45181,45181-2
29,800503,965279248,32013000690815,Z4092VS,46254,46254-1
...,...,...,...,...,...,...
99970,900444,313000894,40003000220570,S6658URM,45500,45500-13
99971,900445,985416373,40003000220571,H0738VVK,45561,45561-2
99972,900446,969332804,40003000220572,R0253LW,45553,45553-4
99973,900447,971328778,40003000220573,Z6443ZDH,40123A,40123A-4
99974,900448,313000867,40003000220574,Y1068LMC,45186,45186-5
99975,900449,965298346,40003000220575,O6165BI,46392,46392-2
99976,900450,313000906,40003000220576,J9268DHC,46200,46200-9
99977,900451,988409288,40003000220577,B6131EP,40553,40553-17
99978,900452,991438371,40003000220578,F7542ML,40555,40555-7
99979,900453,965242754,40003000220579,L5267JY,45571,45571-3
99980,900454,964234749,40003000220580,J9087QTM,45181,45181-2
99981,900455,971308949,40003000220581,Y8726DM,41162,41162-4
99982,900456,966272407,40003000220582,H3533PBT,46261,46261-1
99983,900457,985416373,40003000220583,J1125EJ,45561,45561-2
99984,900458,966251696,40003000220584,B5539HFH,40151B,40151B-2
99985,900459,974363534,40003000220585,C1053KQW,40551,40551-8
99986,900460,989471792,40003000220586,M3084BDD,46100,46100-16
99987,900461,966269860,40003000220587,K6360BLD,40391,40391-4
99988,900462,964170930,40003000220588,J3207HIF,44171,44171-11
99989,900463,966255562,40003000220589,O4991KH,41165B1,41165B1-1
99990,900464,313006918,40003000220590,U5203CKR,40258,40258-12
99991,900465,968286860,40003000220591,M3859RJ,46153,46153-2
99992,900466,964234749,40003000220592,C4190BLY,45181,45181-2
99993,900467,966303118,40003000220593,E5387AYT,45194,45194-2
99994,900468,969296459,40003000220594,S6339UVM,40153A,40153A-4
99995,900469,970328837,40003000220595,C0640JOW,40153A,40153A-6
99996,900470,963239648,40003000220596,S9178RO,45163,45163-1
99997,900471,315006971,40003000220597,R1714OC,46100,46100-4
99998,900472,976385703,40003000220598,G4914IK,46387,46387-5
99999,900473,978384544,40003000220599,B4717IWQ,45587,45587-5

We replace every column's values in df2 with the corresponding index from the appropriate table

In [141]:
# Get all the filenames of the individual CSV files
for filename in os.listdir(write_folder):
    if filename==write_folder+".csv" or filename=="main_table.csv":
        continue
    print(filename)
    # Read the CSV file
    df3 = pd.read_csv(write_folder+"//"+filename)
    # Get the list of columns
    columns = list(df3)
    # Create a Dict to map the column values to an index
    dict3 ={}
    for index, row in df3.iterrows():
        dict3[row[columns[1]]] = row[columns[0]]
    # Map the column values to the dict
    df2[columns[1]] = df2[columns[1]].map(dict3)

branches.csv
counters.csv
customer.csv
staff_ids.csv
transaction_details.csv
vehicles.csv

In [142]:
df2

       transaction_id  staff_id  cust_id  plate_no  branch_id  counter_id
0                 1.0       1.0      1.0       1.0        1.0         1.0
1                 2.0       2.0      2.0       2.0        2.0         2.0
2                 3.0       3.0      3.0       3.0        3.0         3.0
3                 4.0       4.0      4.0       4.0        4.0         4.0
4                 5.0       5.0      5.0       5.0        5.0         5.0
5                 6.0       6.0      6.0       6.0        6.0         6.0
6                 7.0       7.0      7.0       7.0        7.0         7.0
7                 8.0       8.0      8.0       8.0        8.0         8.0
8                 9.0       9.0      9.0       9.0        9.0         9.0
9                10.0      10.0     10.0      10.0       10.0        10.0
10               11.0      11.0     11.0      11.0       11.0        11.0
11               12.0      12.0     12.0      12.0       12.0        12.0
12               13.0      13.0     13.0      13.0        8.0        13.0
13               14.0      14.0     14.0      14.0       13.0        14.0
14               15.0       1.0     15.0      15.0        1.0         1.0
15               16.0      15.0     16.0      16.0       14.0        15.0
16               17.0      16.0     17.0      17.0       15.0        16.0
17               18.0      17.0     18.0      18.0       16.0        17.0
18               19.0      18.0     19.0      19.0       17.0        18.0
19               20.0      19.0     20.0      20.0       18.0        19.0
20               21.0      20.0     21.0      21.0       19.0        20.0
21               22.0      21.0     22.0      22.0       20.0        21.0
22               23.0      22.0     23.0      23.0       21.0        22.0
23               24.0      23.0     24.0      24.0       22.0        23.0
24               25.0      24.0     25.0      25.0       23.0        24.0
25               26.0      25.0     26.0      26.0       24.0        25.0
26               27.0      26.0     27.0      27.0       25.0        26.0
27               28.0      27.0     28.0      28.0       26.0        27.0
28               29.0      23.0     29.0      29.0       22.0        23.0
29               30.0      28.0     30.0      30.0       27.0        28.0
...               ...       ...      ...       ...        ...         ...
99970         99971.0      98.0  54588.0   54566.0       82.0        98.0
99971         99972.0      62.0  54589.0   54567.0       57.0        62.0
99972         99973.0     104.0  54590.0   54568.0       87.0       104.0
99973         99974.0     578.0  54591.0   54569.0      147.0       578.0
99974         99975.0      16.0  54592.0   54570.0       15.0        16.0
99975         99976.0     638.0  54593.0   54571.0      354.0       638.0
99976         99977.0      46.0  54594.0   54572.0       23.0        46.0
99977         99978.0     136.0  54595.0   54573.0        3.0       136.0
99978         99979.0     133.0  54596.0   54574.0       92.0       133.0
99979         99980.0      29.0  54597.0   54575.0       28.0        29.0
99980         99981.0      23.0  54598.0   54576.0       22.0        23.0
99981         99982.0      95.0  54599.0   54577.0       81.0        95.0
99982         99983.0       1.0  54600.0   54578.0        1.0         1.0
99983         99984.0      62.0  54601.0   54579.0       57.0        62.0
99984         99985.0     370.0  54602.0   54580.0      231.0       370.0
99985         99986.0     445.0  54603.0   54581.0      280.0       445.0
99986         99987.0     377.0  54604.0   54582.0        7.0       377.0
99987         99988.0     242.0  54605.0   54583.0      179.0       242.0
99988         99989.0     189.0  54606.0   54584.0      148.0       189.0
99989         99990.0     112.0  54607.0   54585.0       94.0       112.0
99990         99991.0     208.0  54608.0   54586.0       68.0       208.0
99991         99992.0     135.0  54609.0   54587.0      109.0       135.0
99992         99993.0      23.0  54610.0   54588.0       22.0        23.0
99993         99994.0     285.0  54611.0   54589.0      206.0       285.0
99994         99995.0     416.0  54612.0   54590.0      151.0       416.0
99995         99996.0     363.0  54613.0   54591.0      151.0       363.0
99996         99997.0     493.0  54614.0   54592.0      297.0       493.0
99997         99998.0     123.0  54615.0   54593.0        7.0       123.0
99998         99999.0     127.0  54616.0   54594.0       12.0       127.0
99999             NaN      63.0      NaN       NaN       30.0        63.0

[100000 rows x 6 columns]

In [143]:
df2 = df2.dropna().reset_index(drop=True)

In [144]:
# df2.dropna(inplace=True)

Save DF2 into a table

In [145]:
df2.shift()[1:].to_csv(write_folder+"//main_table.csv",index=True,index_label = "Index",float_format="%.10g")

In [163]:
df2

       transaction_id  staff_id  cust_id  plate_no  branch_id  counter_id
0                 1.0       1.0      1.0       1.0        1.0         1.0
1                 2.0       2.0      2.0       2.0        2.0         2.0
2                 3.0       3.0      3.0       3.0        3.0         3.0
3                 4.0       4.0      4.0       4.0        4.0         4.0
4                 5.0       5.0      5.0       5.0        5.0         5.0
5                 6.0       6.0      6.0       6.0        6.0         6.0
6                 7.0       7.0      7.0       7.0        7.0         7.0
7                 8.0       8.0      8.0       8.0        8.0         8.0
8                 9.0       9.0      9.0       9.0        9.0         9.0
9                10.0      10.0     10.0      10.0       10.0        10.0
10               11.0      11.0     11.0      11.0       11.0        11.0
11               12.0      12.0     12.0      12.0       12.0        12.0
12               13.0      13.0     13.0      13.0        8.0        13.0
13               14.0      14.0     14.0      14.0       13.0        14.0
14               15.0       1.0     15.0      15.0        1.0         1.0
15               16.0      15.0     16.0      16.0       14.0        15.0
16               17.0      16.0     17.0      17.0       15.0        16.0
17               18.0      17.0     18.0      18.0       16.0        17.0
18               19.0      18.0     19.0      19.0       17.0        18.0
19               20.0      19.0     20.0      20.0       18.0        19.0
20               21.0      20.0     21.0      21.0       19.0        20.0
21               22.0      21.0     22.0      22.0       20.0        21.0
22               23.0      22.0     23.0      23.0       21.0        22.0
23               24.0      23.0     24.0      24.0       22.0        23.0
24               25.0      24.0     25.0      25.0       23.0        24.0
25               26.0      25.0     26.0      26.0       24.0        25.0
26               27.0      26.0     27.0      27.0       25.0        26.0
27               28.0      27.0     28.0      28.0       26.0        27.0
28               29.0      23.0     29.0      29.0       22.0        23.0
29               30.0      28.0     30.0      30.0       27.0        28.0
...               ...       ...      ...       ...        ...         ...
99966         99970.0     165.0  54587.0   54565.0      133.0       165.0
99967         99971.0      98.0  54588.0   54566.0       82.0        98.0
99968         99972.0      62.0  54589.0   54567.0       57.0        62.0
99969         99973.0     104.0  54590.0   54568.0       87.0       104.0
99970         99974.0     578.0  54591.0   54569.0      147.0       578.0
99971         99975.0      16.0  54592.0   54570.0       15.0        16.0
99972         99976.0     638.0  54593.0   54571.0      354.0       638.0
99973         99977.0      46.0  54594.0   54572.0       23.0        46.0
99974         99978.0     136.0  54595.0   54573.0        3.0       136.0
99975         99979.0     133.0  54596.0   54574.0       92.0       133.0
99976         99980.0      29.0  54597.0   54575.0       28.0        29.0
99977         99981.0      23.0  54598.0   54576.0       22.0        23.0
99978         99982.0      95.0  54599.0   54577.0       81.0        95.0
99979         99983.0       1.0  54600.0   54578.0        1.0         1.0
99980         99984.0      62.0  54601.0   54579.0       57.0        62.0
99981         99985.0     370.0  54602.0   54580.0      231.0       370.0
99982         99986.0     445.0  54603.0   54581.0      280.0       445.0
99983         99987.0     377.0  54604.0   54582.0        7.0       377.0
99984         99988.0     242.0  54605.0   54583.0      179.0       242.0
99985         99989.0     189.0  54606.0   54584.0      148.0       189.0
99986         99990.0     112.0  54607.0   54585.0       94.0       112.0
99987         99991.0     208.0  54608.0   54586.0       68.0       208.0
99988         99992.0     135.0  54609.0   54587.0      109.0       135.0
99989         99993.0      23.0  54610.0   54588.0       22.0        23.0
99990         99994.0     285.0  54611.0   54589.0      206.0       285.0
99991         99995.0     416.0  54612.0   54590.0      151.0       416.0
99992         99996.0     363.0  54613.0   54591.0      151.0       363.0
99993         99997.0     493.0  54614.0   54592.0      297.0       493.0
99994         99998.0     123.0  54615.0   54593.0        7.0       123.0
99995         99999.0     127.0  54616.0   54594.0       12.0       127.0

[99996 rows x 6 columns]

In [164]:
staff_to_transaction= df2[["staff_id","transaction_id"]]

staff_to_transaction.to_csv(write_folder+"//staff_to_transaction.csv",
                            index=False,
                            header  = [":START_ID(Staff)",":END_ID(Transaction)"],
                            float_format="%.10g")

In [165]:
staff_to_counter= df2[["staff_id","counter_id"]]

staff_to_counter.drop_duplicates(subset="staff_id").to_csv(write_folder+"//staff_to_counter.csv",
                            index=False,
                            header  = [":START_ID(Staff)",":END_ID(Counter)"],
                            float_format="%.10g")

In [166]:
staff_to_branch= df2[["staff_id","branch_id"]]
staff_to_branch.drop_duplicates(subset="staff_id").to_csv(write_folder+"//staff_to_branch.csv",
                            index=False,
                            header  = [":START_ID(Staff)",":END_ID(Branch)"],
                            float_format="%.10g")

In [167]:
transaction_to_counter= df2[["transaction_id","counter_id"]]

transaction_to_counter.to_csv(write_folder+"//transaction_to_counter.csv",
                            index=False,
                            header  = [":START_ID(Transaction)",":END_ID(Counter)"],
                            float_format="%.10g")

In [168]:
customer_to_transaction= df2[["cust_id","transaction_id"]]

customer_to_transaction.to_csv(write_folder+"//customer_to_transaction.csv",
                            index=False,
                            header  = [":START_ID(Customer)",":END_ID(Transaction)"],
                            float_format="%.10g")

In [169]:
counter_to_branch= df2[["counter_id","branch_id"]]
counter_to_branch.drop_duplicates(subset="counter_id").to_csv(write_folder+"//counter_to_branch.csv",
                            index=False,
                            header  = [":START_ID(Counter)",":END_ID(Branch)"],
                            float_format="%.10g")

In [170]:
vehicle_to_customer= df2[["plate_no","cust_id"]]
vehicle_to_customer.drop_duplicates(subset="plate_no").to_csv(write_folder+"//vehicle_to_customer.csv",
                            index=False,
                            header  = [":START_ID(Vehicle)",":END_ID(Customer)"],
                            float_format="%.10g")